// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtalN3fLyfcE62cP3v0mF7PAdnXK9qvU0',
    appId: '1:317327670192:web:05798cf7ffc432748eb475',
    messagingSenderId: '317327670192',
    projectId: 'my-assistelefoni',
    authDomain: 'my-assistelefoni.firebaseapp.com',
    databaseURL: 'https://my-assistelefoni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-assistelefoni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cojkxk9JVOBRu_XQN_6g-VXNvCpM5IY',
    appId: '1:317327670192:android:9fae45b1e14b559b8eb475',
    messagingSenderId: '317327670192',
    projectId: 'my-assistelefoni',
    databaseURL: 'https://my-assistelefoni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-assistelefoni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQZ9UOJJvKTA5QhGacjwnAfAB_VusC9-s',
    appId: '1:317327670192:ios:f66d21a2cec937ca8eb475',
    messagingSenderId: '317327670192',
    projectId: 'my-assistelefoni',
    databaseURL: 'https://my-assistelefoni-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-assistelefoni.appspot.com',
    iosClientId: '317327670192-6q0ofidg6mj49umjrni31014p2n8kvuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
